# Generated by Django 4.2.5 on 2023-11-16 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='services',
            new_name='product',
        ),
    ]
