# Generated by Django 4.2.5 on 2023-11-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(default='https://placehold.co/500x300', max_length=30, null=True),
        ),
    ]
