# Generated by Django 4.2.7 on 2023-11-17 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0010_alter_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='item',
            new_name='product',
        ),
    ]
