# Generated by Django 4.2.7 on 2023-11-18 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0012_purchase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
